### ISSUE TITLE
Probleme mit dem Code!!

### ISSUE THREAD

**Issue by MiguelKliem91** [Nils-DataCraft/Tagesaufgaben_GIT_Erste_Commits#2]
print("Wunderschöner Tag heute, oder?")
**Der Code ist viel zu einfach**
print("Heute regnet es leider.")

print("Hallo")

def meine_funktion():
    print("Hallo")

**Comment by lisabeller** [comment]
@MiguelKliem91

**Comment by lisabeller** [comment]
@MiguelKliem91 
print("Gerade regnet es, wo ist die Sonne?")

**Comment by Nils-DataCraft** [comment]
Behoben in d95e3876ed7708249ddf0a659c93a8ddfad594fd. Siehe auch #9
