### ISSUE TITLE
Code funktioniert nicht

### ISSUE THREAD

**Issue by lisabeller** [Nils-DataCraft/Tagesaufgaben_GIT_Erste_Commits#3]
Bitte ein neues Python-Skript hinzufügen mit neuer Funktion, die ein Pieplot enthält @nhoeche

**Comment by Nils-DataCraft** [comment]
Hab leider zu wenig Zeit! Muss @kfcal machen

**Comment by lisabeller** [comment]
@kfcal Kannst du den Task bestätigen?

**Comment by kfcal** [comment]
Ich schätze, da ist eher die Expertise von @Alexander-Greif gefragt.

**Comment by Nils-DataCraft** [comment]
Um @Alexander-Greif zum Task zuweisen zu können muss er Kollaborator sein, oder hier kommentiert haben
