### ISSUE TITLE
Unendlich viele Möglichkeiten?

### ISSUE THREAD

**Issue by iManu93** [Nils-DataCraft/Tagesaufgaben_GIT_Erste_Commits#5]
Warum gibt es 20 Möglichkeiten, neue Repositories zu erstellen/bearbeiten/hochzuladen/...?
Ich wäre dafür, alles nur noch über Binärcode einzustellen. Ist doch viel einfacher!!111

01000100 01100101 01100101 01100110 01100101 00100000 01000111 01110100 11111010 11101111 01100101
- Manuel

**Comment by Nils-DataCraft** [comment]
Danke für den Vorschlag!

01000100 01100101 01100101 01100110 01100101 00100000 01000111 01110100 11111010 11101111 01100101
  |
 V
Deefe Gtúïe. (?)

![image](https://github.com/Nils-DataCraft/Tagesaufgaben_GIT_Erste_Commits/assets/141046791/cebcfb16-6741-4d10-90a8-382ab7c71dc4)

**Comment by Nils-DataCraft** [comment]
https://xkcd.com/927/
