### ISSUE TITLE
PIZZA - Antilopen - Gang

### ISSUE THREAD

**Issue by SaschaS1993** [Nils-DataCraft/Tagesaufgaben_GIT_Erste_Commits#6]
[Part 1: Koljah]
Diese Welt zerfällt - überall Krisen oder Krieg
[Die Bienen sterben, Terror in Brüssel und Paris](https://genius.com/11126043/Antilopen-gang-pizza/Die-bienen-sterben-terror-in-brussel-und-paris)
[Die Pole schmelzen, die Regierung macht die Grenzen dicht](https://genius.com/11137693/Antilopen-gang-pizza/Die-pole-schmelzen-die-regierung-macht-die-grenzen-dicht)
[Xavier singt, in Europa wird nach rechts gerückt](https://genius.com/11131177/Antilopen-gang-pizza/Xavier-singt-in-europa-wird-nach-rechts-geruckt)
Das ist echt verrückt! Leute, ist das nötig?
Frieden auf der Welt wär' von heut auf morgen möglich
Ah yeah, wir alle hier sind gleich
Und wir wollen auch das Gleiche - ich kann es dir beweisen:
Es klingelt an der Tür, dann kommt der Lieferant
Mit dem dampfenden Symbol unsrer Hoffnung in der Hand
Die heilige Scheibe, die alle vereint
Die Weisheit der Menschheit, gebacken in Teig

[Hook: Danger Dan]
Oh, ich glaube fest daran
Dass uns Pizza retten kann!
Sie verbündet diese Welt
Baby, lass uns Pizza bestell'n!
Oh, ich glaube fest daran
Dass uns Pizza retten kann!
Jeder Revolutionär
Braucht nur Pizza und Gewehr!

[Part 2: Danger Dan]
Es geht nicht um Herkunft, Hautfarbe und Religion
Hauptsache, der Teig ist dünn; Hauptsache, Tomatensoße
Hauptsache, Käse; die Welt ist eine Scheibe
Wer grade Pizza isst, tut keinem Menschen was zuleide
Auf jedem Kontinent und in jeder Kultur
[Findest du sowas wie Pizza oder ein Pendant dazu](https://genius.com/11131149/Antilopen-gang-pizza/Findest-du-sowas-wie-pizza-oder-ein-pendant-dazu)
[Es geht von Tansania bis zur Münchner Schickeria](https://genius.com/11131035/Antilopen-gang-pizza/Es-geht-von-tansania-bis-zur-munchner-schickeria)
Eines Tages wird die ganze Welt zu einer Pizzeria
In jeder Stadt und in jedem Land
Schreibt die Parole an jede Wand!
[„Viva la Margherita! Hoch die Calzone!](https://genius.com/11131013/Antilopen-gang-pizza/Viva-la-margherita-hoch-die-calzone)
[Feuer und Flamme dem Holzkohleofen!](https://genius.com/11128829/Antilopen-gang-pizza/Feuer-und-flamme-dem-holzkohleofen)“
See upcoming rap shows
Get tickets for your favorite artists
You might also like
FloyyMenor & Cris Mj - Gata Only (Deutsche Übersetzung)
Genius Deutsche Übersetzungen
Family Matters
Drake
​euphoria
Kendrick Lamar
[Hook: Danger Dan]
Oh, ich glaube fest daran
Dass uns Pizza retten kann!
Sie verbündet diese Welt
Baby, lass uns Pizza bestell'n!
Oh, ich glaube fest daran
Dass uns Pizza retten kann!
Jeder Revolutionär
Braucht nur Pizza und Gewehr!

[Part 3: Panik Panzer]
Wenn du mal Probleme hast und wieder mal die Bull'n komm'n
[Ist tiefgekühlte Pizza auch ein wunderbares Wurfgeschoss](https://genius.com/11356994/Antilopen-gang-pizza/Ist-tiefgekuhlte-pizza-auch-ein-wunderbares-wurfgeschoss)
Wenn sie dich erwischt hab'n, du sitzt im Gerichtssaal
Vergiss nicht: den Richter besticht man mit Pizza!
Wenn es nicht klappt und du fährst ein in den Knast
Dann wird einfach eine Feile in den Teig reingebacken
Pizza ist das Mittel ganze Staaten zu stürzen
Vergiss sie bitte nicht mit [Oregano zu würzen](https://genius.com/11357000/Antilopen-gang-pizza/Oregano-zu-wurzen)

[Hook: Danger Dan]
Oh, ich glaube fest daran
Dass uns Pizza retten kann!
Sie verbündet diese Welt
Baby, lass uns Pizza bestell'n!
Oh, ich glaube fest daran
Dass uns Pizza retten kann!
Jeder Revolutionär
Braucht nur Pizza und Gewehr!
Oh, ich glaube fest daran
Dass uns Pizza retten kann!
Sie verbündet diese Welt
Baby, lass uns Pizza bestell'n!
Oh, ich glaube fest daran
Dass uns Pizza retten kann!
Jeder Revolutionär
Braucht nur Pizza und Gewehr![Part 1: Koljah]
Diese Welt zerfällt - überall Krisen oder Krieg
[Die Bienen sterben, Terror in Brüssel und Paris](https://genius.com/11126043/Antilopen-gang-pizza/Die-bienen-sterben-terror-in-brussel-und-paris)
[Die Pole schmelzen, die Regierung macht die Grenzen dicht](https://genius.com/11137693/Antilopen-gang-pizza/Die-pole-schmelzen-die-regierung-macht-die-grenzen-dicht)
[Xavier singt, in Europa wird nach rechts gerückt](https://genius.com/11131177/Antilopen-gang-pizza/Xavier-singt-in-europa-wird-nach-rechts-geruckt)
Das ist echt verrückt! Leute, ist das nötig?
Frieden auf der Welt wär' von heut auf morgen möglich
Ah yeah, wir alle hier sind gleich
Und wir wollen auch das Gleiche - ich kann es dir beweisen:
Es klingelt an der Tür, dann kommt der Lieferant
Mit dem dampfenden Symbol unsrer Hoffnung in der Hand
Die heilige Scheibe, die alle vereint
Die Weisheit der Menschheit, gebacken in Teig

[Hook: Danger Dan]
Oh, ich glaube fest daran
Dass uns Pizza retten kann!
Sie verbündet diese Welt
Baby, lass uns Pizza bestell'n!
Oh, ich glaube fest daran
Dass uns Pizza retten kann!
Jeder Revolutionär
Braucht nur Pizza und Gewehr!

[Part 2: Danger Dan]
Es geht nicht um Herkunft, Hautfarbe und Religion
Hauptsache, der Teig ist dünn; Hauptsache, Tomatensoße
Hauptsache, Käse; die Welt ist eine Scheibe
Wer grade Pizza isst, tut keinem Menschen was zuleide
Auf jedem Kontinent und in jeder Kultur
[Findest du sowas wie Pizza oder ein Pendant dazu](https://genius.com/11131149/Antilopen-gang-pizza/Findest-du-sowas-wie-pizza-oder-ein-pendant-dazu)
[Es geht von Tansania bis zur Münchner Schickeria](https://genius.com/11131035/Antilopen-gang-pizza/Es-geht-von-tansania-bis-zur-munchner-schickeria)
Eines Tages wird die ganze Welt zu einer Pizzeria
In jeder Stadt und in jedem Land
Schreibt die Parole an jede Wand!
[„Viva la Margherita! Hoch die Calzone!](https://genius.com/11131013/Antilopen-gang-pizza/Viva-la-margherita-hoch-die-calzone)
[Feuer und Flamme dem Holzkohleofen!](https://genius.com/11128829/Antilopen-gang-pizza/Feuer-und-flamme-dem-holzkohleofen)“
See upcoming rap shows
Get tickets for your favorite artists
You might also like
FloyyMenor & Cris Mj - Gata Only (Deutsche Übersetzung)
Genius Deutsche Übersetzungen
Family Matters
Drake
​euphoria
Kendrick Lamar
[Hook: Danger Dan]
Oh, ich glaube fest daran
Dass uns Pizza retten kann!
Sie verbündet diese Welt
Baby, lass uns Pizza bestell'n!
Oh, ich glaube fest daran
Dass uns Pizza retten kann!
Jeder Revolutionär
Braucht nur Pizza und Gewehr!

[Part 3: Panik Panzer]
Wenn du mal Probleme hast und wieder mal die Bull'n komm'n
[Ist tiefgekühlte Pizza auch ein wunderbares Wurfgeschoss](https://genius.com/11356994/Antilopen-gang-pizza/Ist-tiefgekuhlte-pizza-auch-ein-wunderbares-wurfgeschoss)
Wenn sie dich erwischt hab'n, du sitzt im Gerichtssaal
Vergiss nicht: den Richter besticht man mit Pizza!
Wenn es nicht klappt und du fährst ein in den Knast
Dann wird einfach eine Feile in den Teig reingebacken
Pizza ist das Mittel ganze Staaten zu stürzen
Vergiss sie bitte nicht mit [Oregano zu würzen](https://genius.com/11357000/Antilopen-gang-pizza/Oregano-zu-wurzen)

[Hook: Danger Dan]
Oh, ich glaube fest daran
Dass uns Pizza retten kann!
Sie verbündet diese Welt
Baby, lass uns Pizza bestell'n!
Oh, ich glaube fest daran
Dass uns Pizza retten kann!
Jeder Revolutionär
Braucht nur Pizza und Gewehr!
Oh, ich glaube fest daran
Dass uns Pizza retten kann!
Sie verbündet diese Welt
Baby, lass uns Pizza bestell'n!
Oh, ich glaube fest daran
Dass uns Pizza retten kann!
Jeder Revolutionär
Braucht nur Pizza und Gewehr!

**Comment by iManu93** [comment]
Muss ich jetzt ein neues "issue" öffnen, wenn ich dank deinem issue hunger bekommen habe?

**Comment by TreyWhey** [comment]
Muss ich jetzt ein neues "issue" öffnen, wenn ich dank deinem issue Kopfschmerzen hab?

**Comment by Nils-DataCraft** [comment]
Danke für den Vorschlag. Issue geschlossen als Offtopic :D
