### ISSUE TITLE
Ausgaben des Codes

### ISSUE THREAD

**Issue by KarlFriedrich1** [Nils-DataCraft/Tagesaufgaben_GIT_Erste_Commits#9]
Hallo Nils,

leider ist die Funktion der Funktion nicht ganz ausgereift.
Die ersten Printausgaben haben nichts mit der Funktion zu tun.

**Comment by Nils-DataCraft** [comment]
Behoben in d95e3876ed7708249ddf0a659c93a8ddfad594fd
